import { useState } from "react";
import { passApi } from "../../services/passService";
import { QrCode, CheckCircle2, XCircle, ShieldAlert, Loader2, ArrowRight } from "lucide-react";

export default function DriverScannerPage() {
  const [passCodeInput, setPassCodeInput] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);

  const handleVerify = async (e) => {
    e?.preventDefault();
    if (!passCodeInput.trim()) return;

    setLoading(true);
    setResult(null);

    try {
      const res = await passApi.verifyPass(passCodeInput);
      if (res.success && res.data) {
        setResult(res.data);
      } else {
        setResult({ isValid: false, reason: res.message || "Invalid QR Pass." });
      }
    } catch (err) {
      setResult({
        isValid: false,
        reason: err.response?.data?.message || "Failed to verify pass code.",
      });
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto space-y-6">
      {/* Header */}
      <div className="rounded-2xl bg-gradient-to-r from-emerald-600 via-teal-600 to-emerald-800 p-6 text-white shadow-lg">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/20 backdrop-blur">
            <QrCode className="h-6 w-6 text-white" />
          </div>
          <div>
            <h1 className="text-2xl font-bold tracking-tight">
              Driver Pass Verification Console
            </h1>
            <p className="text-xs text-emerald-100">
              Scan or enter student QR boarding pass codes for real-time verification
            </p>
          </div>
        </div>
      </div>

      {/* Input / Scanner Simulation Form */}
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm dark:border-slate-800 dark:bg-slate-900 space-y-4">
        <h3 className="text-base font-bold text-slate-900 dark:text-white">
          Enter / Scan Boarding Pass Code
        </h3>

        <form onSubmit={handleVerify} className="flex gap-2">
          <input
            type="text"
            value={passCodeInput}
            onChange={(e) => setPassCodeInput(e.target.value)}
            placeholder="Enter pass code (e.g. RPASS-STU-8923)"
            className="flex-1 rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-mono font-bold text-slate-900 placeholder:font-sans placeholder:text-slate-400 focus:border-emerald-600 focus:outline-none dark:border-slate-700 dark:bg-slate-950 dark:text-white"
          />

          <button
            type="submit"
            disabled={loading}
            className="flex items-center gap-2 rounded-xl bg-emerald-600 px-6 py-3 text-xs font-bold text-white shadow transition hover:bg-emerald-700 disabled:opacity-50"
          >
            {loading ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <>
                <span>VERIFY</span>
                <ArrowRight className="h-4 w-4" />
              </>
            )}
          </button>
        </form>

        <p className="text-[11px] text-slate-500">
          Tip: Enter exact pass code generated by student (e.g., <span className="font-mono font-bold">RPASS-STU-8923</span>).
        </p>
      </div>

      {/* Verification Result Feedback Cards */}
      {result && (
        <div
          className={`rounded-3xl border-2 p-6 shadow-2xl transition ${
            result.isValid
              ? "border-emerald-500 bg-emerald-50/90 dark:border-emerald-800 dark:bg-emerald-950/70"
              : "border-rose-500 bg-rose-50/90 dark:border-rose-800 dark:bg-rose-950/70"
          }`}
        >
          {result.isValid ? (
            <div className="space-y-4">
              <div className="flex items-center gap-3 border-b border-emerald-200 pb-4 dark:border-emerald-900">
                <CheckCircle2 className="h-10 w-10 text-emerald-600 dark:text-emerald-400 animate-bounce" />
                <div>
                  <h2 className="text-xl font-black text-emerald-900 dark:text-emerald-100">
                    ✅ VALID BOARDING PASS
                  </h2>
                  <p className="text-xs text-emerald-700 dark:text-emerald-300">
                    Pass verified & ride automatically logged to student history.
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-4 rounded-2xl bg-white p-4 text-xs shadow-sm dark:bg-slate-900">
                <div>
                  <span className="text-[10px] uppercase font-bold text-slate-400">Student Name</span>
                  <p className="font-extrabold text-slate-900 dark:text-white text-sm">{result.studentName}</p>
                </div>
                <div>
                  <span className="text-[10px] uppercase font-bold text-slate-400">Student ID</span>
                  <p className="font-extrabold text-slate-900 dark:text-white text-sm">{result.studentId}</p>
                </div>
                <div>
                  <span className="text-[10px] uppercase font-bold text-slate-400">Department</span>
                  <p className="font-bold text-slate-700 dark:text-slate-300">{result.department}</p>
                </div>
                <div>
                  <span className="text-[10px] uppercase font-bold text-slate-400">Approved Route</span>
                  <p className="font-bold text-emerald-600 dark:text-emerald-400">{result.routeName}</p>
                </div>
              </div>

              <div className="flex items-center justify-between text-[11px] text-emerald-800 dark:text-emerald-200 font-mono">
                <span>Pass Code: {result.passCode}</span>
                <span>Verified: {new Date(result.verifiedAt).toLocaleTimeString()}</span>
              </div>
            </div>
          ) : (
            <div className="space-y-3">
              <div className="flex items-center gap-3">
                <XCircle className="h-10 w-10 text-rose-600 dark:text-rose-400 animate-pulse" />
                <div>
                  <h2 className="text-xl font-black text-rose-900 dark:text-rose-100">
                    ❌ INVALID / EXPIRED PASS
                  </h2>
                  <p className="text-xs font-semibold text-rose-700 dark:text-rose-300">
                    Reason: {result.reason}
                  </p>
                </div>
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}
